### ISSUE TITLE
Custom Map

### ISSUE THREAD

**Issue by GUnoahj** [DIT113-V22/group-09#42]
As a user I want a custom made map so that I can try out the features of the program to its full extent.

- [x] Individual models imported and placed appropriately
- [x] Map meshed and import as gltf
- [x] Environment and hitboxes created, export to SMCE
- [x] The implementation is tested

**Comment by RuthgerD** [comment]
I'm doing a round of warnings here, when you do finish this map add the `.import` folder to your gitignore!
